#!/usr/bin/env bash
# A thin wrapper around the Flickr API.  I use this to do experiments
# and quickly check what an API response looks like.
#
# It takes one or two arguments: the API method, plus query parameters
# (if any).  Examples:
#
#     $ flapi flickr.photos.getInfo photo_id=52782497889
#     $ flapi flickr.commons.getInstitutions
#

set -o errexit
set -o nounset

if (( $# == 1 ))
then
  method="$1"
  params=""
elif (( $# == 2 ))
then
  method="$1"
  params="$2"
else
  echo "Usage: $0 <METHOD> [<PARAMS>]" >&2
  exit 1
fi

api_key=$(keyring get flickr_api key || echo '')

if [[ -z "$api_key" ]]
then
  echo "Unable to get Flickr API key from system keychain! " >&2
  echo "Try running \`keyring set flickr_api key\`"          >&2
  exit 1
fi

XML_RESPONSE=$(
  curl --silent --get "https://api.flickr.com/services/rest/" \
    --data "api_key=${api_key}" \
    --data "method=${method}" \
    --data "${params}"
)

# Check if we're running in a Terminal -- only pretty print the response
# with colours if so.
if [ -t 1 ]
then
  echo "$XML_RESPONSE" | xmllint --format - | pygmentize -l xml
else
  echo "$XML_RESPONSE" | xmllint --format -
fi
