#!/usr/bin/env bash
# Look up information about an indiviudual photo.
#
# It takes a Flickr photo ID or URL to a Flickr photo.  Examples:
#
#     $ flphoto https://www.flickr.com/photos/nypl/4058778064/
#     $ flphoto 52783721105
#

set -o errexit
set -o nounset

if (( $# != 1 ))
then
  echo "Usage: $0 <PHOTO_ID>" >&2
  exit 1
fi

USER_INPUT="$1"

if [[ "$USER_INPUT" =~ ^[0-9]+$ ]]
then
  flapi flickr.photos.getInfo photo_id=$USER_INPUT
else
  PHOTO_ID=$(flickr_url_parser "$USER_INPUT" | jq -r .photo_id)

  if [[ "$PHOTO_ID" =~ ^[0-9]+$ ]]
  then
    flapi flickr.photos.getInfo photo_id=$PHOTO_ID
  else
    echo "I don't know how to interpret $USER_INPUT" >&2
    exit 1
  fi
fi
