name: Test

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: dev_requirements.txt

    - name: Install dependencies
      run: pip install -r dev_requirements.txt

    - name: Check formatting
      run: |
        ruff check .
        ruff format --check .

    - name: Check docstrings
      run: interrogate -vv

    - name: Check types
      run: mypy tests

    - name: Add repo to PATH
      run: echo "$(git rev-parse --show-toplevel)" >> $GITHUB_PATH

    - name: Run tests
      run: |
        python3 -c 'import keyring, os; keyring.set_password("flickr_api", "key", os.environ["FLICKR_API_KEY"])'
        py.test tests
      env:
        FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}

      # Dependabot doesn't have access to the secrets, so this will fail --
      # but that's probably okay.  The tests will run when we merge to main
      # so we'll still find out quickly if they don't work, but we won't
      # have a red X to dismiss in the GitHub UI.
      #
      # This is a bit fragile because it means PRs from third parties who
      # aren't Dependabot will fail in the same way -- but that doesn't
      # seem like it'll be a frequent occurrence, so this is good enough
      # for now.
      #
      # See https://github.com/Flickr-Foundation/flapi.sh/issues/9
      if: github.triggering_actor != 'dependabot[bot]'
